<a href="https://colab.research.google.com/github/Mez-MohamedRafik/SMS-Text-Classification/blob/main/FCC_sms_text_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import tensorflow as tf
import pandas as pd
from tensorflow import keras
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.20.0

In [ ]:
# get data files
!wget https://cdn.freecodecamp.org/project-data/sms/train-data.tsv
!wget https://cdn.freecodecamp.org/project-data/sms/valid-data.tsv

train_file_path = "train-data.tsv"
test_file_path = "valid-data.tsv"

--2026-09-08 14:08:06--  https://cdn.freecodecamp.org/project-data/sms/train-data.tsv
Resolving cdn.freecodecamp.org (cdn.freecodecamp.org)... 104.26.2.33, 172.67.70.149, 104.26.3.33, ...
Connecting to cdn.freecodecamp.org (cdn.freecodecamp.org)|104.26.2.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 358233 (350K) [text/tab-separated-values]
Saving to: ‘train-data.tsv’

train-data.tsv      100%[===================>] 349.84K  --.-KB/s    in 0.02s

2026-09-08 14:08:06 (14.5 MB/s) - ‘train-data.tsv’ saved [358233/358233]

--2026-09-08 14:08:06--  https://cdn.freecodecamp.org/project-data/sms/valid-data.tsv
Resolving cdn.freecodecamp.org (cdn.freecodecamp.org)... 104.26.2.33, 172.67.70.149, 104.26.3.33, ...
Connecting to cdn.freecodecamp.org (cdn.freecodecamp.org)|104.26.2.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 118774 (116K) [text/tab-separated-values]
Saving to: ‘valid-data.tsv’

valid-data.tsv      100%[===================>] 115.99K  --.-KB/s    in 0.009s

2026-09-08 14:08:06 (13.0 MB/s) - ‘valid-data.tsv’ saved [118774/118774]

In [ ]:
train_df = pd.read_csv(train_file_path, sep='\t', header=None, names=['label', 'message'])
test_df = pd.read_csv(test_file_path, sep='\t', header=None, names=['label', 'message'])

In [ ]:
print('Training data head:')
display(train_df.head())

Training data head:

  label                                            message
0   ham  ahhhh...just woken up!had a bad dream about u ...
1   ham                           you can never do nothing
2   ham  now u sound like manky scouse boy steve,like! ...
3   ham  mum say we wan to go then go... then she can s...
4   ham  never y lei... i v lazy... got wat? dat day ü ...

In [ ]:
print('Test data head:')
display(test_df.head())

Test data head:

  label                                            message
0   ham  i am in hospital da. . i will return home in e...
1   ham         not much, just some textin'. how bout you?
2   ham  i probably won't eat at all today. i think i'm...
3   ham  don‘t give a flying monkeys wot they think and...
4   ham                                who are you seeing?

In [ ]:
train_df['label'] = train_df['label'].map({'ham': 0, 'spam': 1})
test_df['label'] = test_df['label'].map({'ham': 0, 'spam': 1})

display(train_df.head())

   label                                            message
0      0  ahhhh...just woken up!had a bad dream about u ...
1      0                           you can never do nothing
2      0  now u sound like manky scouse boy steve,like! ...
3      0  mum say we wan to go then go... then she can s...
4      0  never y lei... i v lazy... got wat? dat day ü ...

In [ ]:

display(test_df.head())

   label                                            message
0      0  i am in hospital da. . i will return home in e...
1      0         not much, just some textin'. how bout you?
2      0  i probably won't eat at all today. i think i'm...
3      0  don‘t give a flying monkeys wot they think and...
4      0                                who are you seeing?

In [ ]:

train_df['label'].value_counts()

label
0    3619
1     560
Name: count, dtype: int64

In [ ]:
from tensorflow.keras.layers import TextVectorization

vocab_size = 2000
max_len = 50

vectorizer = TextVectorization(
    max_tokens = vocab_size,
    output_mode = 'int',
    output_sequence_length = max_len
)

In [ ]:
train_df.head()

   label                                            message
0      0  ahhhh...just woken up!had a bad dream about u ...
1      0                           you can never do nothing
2      0  now u sound like manky scouse boy steve,like! ...
3      0  mum say we wan to go then go... then she can s...
4      0  never y lei... i v lazy... got wat? dat day ü ...

In [ ]:
vectorizer.adapt(train_df['message'])
X_train = vectorizer(train_df['message'])
Y_train = train_df['label']
X_test = vectorizer(test_df['message'])
Y_test = test_df['label']

In [ ]:
X_train[0]

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([  1,   1,   1,   5, 404, 824,  79,   7,   1,   3,  47,  57,   7,
       153,  22,   3, 177,  56, 165,  79,   1, 107,  26,   3, 302,  23,
        43,  13,  16,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])>

In [ ]:
from tensorflow.keras.layers import TextVectorization
temp = TextVectorization()
temp.adapt(train_df['message'])
print(len(temp.get_vocabulary()))

8181

In [ ]:
from collections import Counter

all_words = []
for message in train_df['message']:
    words = message.lower().split()
    all_words.extend(words)

word_counts = Counter(all_words)

print("total unique words:", len(word_counts))
print("words appearing >=2 times:", sum(1 for c in word_counts.values() if c >= 2))
print("words appearing >=5 times:", sum(1 for c in word_counts.values() if c >= 5))
print("words appearing >=10 times:", sum(1 for c in word_counts.values() if c >= 10))

print(word_counts.most_common(10))

total unique words: 11330
words appearing >=2 times: 4401
words appearing >=5 times: 1649
words appearing >=10 times: 843
[('to', 1670), ('i', 1633), ('you', 1451), ('a', 1052), ('the', 1000), ('u', 729), ('and', 712), ('in', 651), ('is', 643), ('my', 569)]

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

Embedding_dim = 16

model = Sequential([
    Embedding(input_dim = vocab_size, output_dim = Embedding_dim),
    LSTM(32),
    Dense(1, activation = 'sigmoid')
 ])

model.compile(
    loss = 'binary_crossentropy',
    optimizer = 'adam',
    metrics = ['accuracy']
)

model(X_train[:1])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (1, 50, 16)            │        32,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (1, 32)                │         6,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (1, 1)                 │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 38,305 (149.63 KB)

 Trainable params: 38,305 (149.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)


history = model.fit(
    X_train, Y_train,
    validation_data = (X_test, Y_test),
    epochs = 30,
    callbacks = [early_stop],
    verbose = 2
)

Epoch 1/30
131/131 - 4s - 32ms/step - accuracy: 0.9780 - loss: 0.1023 - val_accuracy: 0.9591 - val_loss: 0.1581
Epoch 2/30
131/131 - 3s - 24ms/step - accuracy: 0.9787 - loss: 0.0997 - val_accuracy: 0.9605 - val_loss: 0.1547
Epoch 3/30
131/131 - 3s - 21ms/step - accuracy: 0.9797 - loss: 0.0954 - val_accuracy: 0.9066 - val_loss: 0.2999
Epoch 4/30
131/131 - 3s - 26ms/step - accuracy: 0.8325 - loss: 0.3445 - val_accuracy: 0.8657 - val_loss: 0.3434
Epoch 5/30
131/131 - 4s - 31ms/step - accuracy: 0.8660 - loss: 0.3361 - val_accuracy: 0.8657 - val_loss: 0.3494

In [ ]:
loss, acc = model.evaluate(X_test, Y_test, verbose=0)
print(loss, acc)

0.1547269970178604 0.960488498210907

In [ ]:

def predict_message(pred_text):
  prediction = []
  vectorized = vectorizer([pred_text])
  prediction = model.predict(vectorized)
  probability = float(prediction[0][0])
  label = "spam" if probability >= 0.5 else "ham"
  prediction = [probability, label]

  return (prediction)

pred_text = "how are you doing today?"

prediction = predict_message(pred_text)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step
[0.01740250363945961, 'ham']

In [ ]:
# Run this cell to test your function and model. Do not modify contents.
def test_predictions():
  test_messages = ["how are you doing today",
                   "sale today! to stop texts call 98912460324",
                   "i dont want to go. can we try it a different day? available sat",
                   "our new mobile video service is live. just install on your phone to start watching.",
                   "you have won £1000 cash! call to claim your prize.",
                   "i'll bring it tomorrow. don't forget the milk.",
                   "wow, is your arm alright. that happened to me one time too"
                  ]

  test_answers = ["ham", "spam", "ham", "spam", "spam", "ham", "ham"]
  passed = True

  for msg, ans in zip(test_messages, test_answers):
    prediction = predict_message(msg)
    if prediction[1] != ans:
      passed = False

  if passed:
    print("You passed the challenge. Great job!")
  else:
    print("You haven't passed yet. Keep trying.")

test_predictions()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
You passed the challenge. Great job!